config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: "Login", sign_out: "Logout", sign_up: "Register"}
  resources :portfolios, except: [:show]
  get "angular-items", to: "portfolios#angular"
  get "portfolios/:id", to: "portfolios#show", as: "portfolio_show"
  
  get "about-me", to: "pages#about"
  
  get "contact", to: "pages#contact"

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  root to: "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: lambda {|attrs| attrs["name"].blank? }
  
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image
  
  def self.angular
    where(subtitle: "Angular")
  end
  
  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails")}
  
  after_initialize :set_defaults
  
  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: 600, width: 400)
    self.thumb_image ||= Placeholder.image_generator(height: 350, width: 200)
  end
  
  
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  def index
    @portfolio_items = Portfolio.all
  end
 
  def angular
    @angular_portfolio_items = Portfolio.angular
  end
  
 def new
  @portfolio_item = Portfolio.new
  3.times { @portfolio_item.technologies.build }
 end
 
  def create
   @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your Portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit 
  end
  
  def update
   
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The Portfolio successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def show
  end 
  
  def destroy
    
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was successfully destroyed.' }
   end 
  end
  private
  
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                      technologies_attributes: [:name]
                                    )
  end
  
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <h2 style="font-family: Cursive">Technologies</h2>
  
  <ul>
    <%= f.fields_for :technologies do |technology_form| %>
    <li>
      <%= technology_form.label :name %>
      <%= technology_form.text_field :name %>
    </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>

<p><%= portfolio_item.subtitle %></p>

<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to "delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: {confirm: "Are you sure?"} if logged_in?(:site_admin) %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_path %>
<% @angular_portfolio_items.each do |portfolio_item| %>
  <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) if logged_in?(:site_admin) %></p>
  <p><%= portfolio_item.subtitle %></p>
  <p><%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil?%>
  <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
  <%= link_to 'Delete portfolio item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this portfolio item</h1>

<%= render"form", portfolio_item: @portfolio_item %>

app/views/portfolios/index.html.erb
<h1>Portfolio items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<%= render partial: 'portfolio_item', collection: @portfolio_items %>

app/views/portfolios/new.html.erb
<h1>Create a new portfolio item</h1>

<%= render"form", portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil?%>

<h1><%= @portfolio_item.title %></h1>

<em><%= @portfolio_item.subtitle %></em>

<p><%= @portfolio_item.body %></p>

<h1>Technologies Used:</h1>

<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>